### ISSUE TITLE
[logs error] "docker logs" requires exactly 1 argument(s).

### ISSUE THREAD

**Issue by WayneUong** [zodern/meteor-up#240]
```
mup logs

[xx.xx.xx.xx]"docker logs" requires exactly 1 argument(s).
See 'docker logs --help'.

Usage:  docker logs [OPTIONS] CONTAINER

Fetch the logs of a container
```

The same settings work with `mupx`

**Comment by eric-burel** [comment]
Same issue with Meteor 1.4.1. The container must be specified, as the app uses at least two containers (one for Meteor and one for Mongo).

**Comment by eric-burel** [comment]
It seems to have been solved by last version 1.0.2

**Comment by lfilho** [comment]
I'm using the last version as of this writing and still having this issue.
