### ISSUE TITLE
How I can set timezone to container in deploying ?

### ISSUE THREAD

**Issue by eportico** [zodern/meteor-up#377]
How I can set timezone to container in deploying ?
thx

**Comment by eportico** [comment]
Resolved:
In mup.js

  docker: {
      image: 'abernix/meteord:base',
      args: ["-v /etc/timezone:/etc/timezone","-v /etc/localtime:/etc/localtime"]
    },

**Comment by YunaiV** [comment]
@eportico hi?can you tell me which os did you used? ubuntu or centos 6 or centos7?

**Comment by thearabbit** [comment]
I still have problem with this.
I stay in `Asia/Phnom_Penh`.
Please help me.
