### ISSUE TITLE
nofat make failing

### ISSUE THREAD

**Issue by unmonk** [zodern/meteor-up#98]
Failing to run the prepublish script (nofat make) 

> `Error: Couldn't find preset "stage-3" relative to directory "/home/sweaver/meteor-up/src"
>     at /home/sweaver/meteor-up/node_modules/babel-core/lib/transformation/file/options/option-manager.js:372:17
>     at Array.map (native)
>     at OptionManager.resolvePresets (/home/sweaver/meteor-up/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
>     at OptionManager.mergePresets (/home/sweaver/meteor-up/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
>     at OptionManager.mergeOptions (/home/sweaver/meteor-up/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
>     at OptionManager.init (/home/sweaver/meteor-up/node_modules/babel-core/lib/transformation/file/options/option-manager.js:465:10)
>     at File.initOptions (/home/sweaver/meteor-up/node_modules/babel-core/lib/transformation/file/index.js:194:75)
>     at new File (/home/sweaver/meteor-up/node_modules/babel-core/lib/transformation/file/index.js:123:22)
>     at Pipeline.transform (/home/sweaver/meteor-up/node_modules/babel-core/lib/transformation/pipeline.js:45:16)
>     at /home/sweaver/meteor-up/node_modules/babel-core/lib/api/node.js:106:18
> 
> npm ERR! Linux 3.13.0-79-generic
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "prepublish"
> npm ERR! node v4.4.2
> npm ERR! npm  v2.15.0
> npm ERR! code ELIFECYCLE
> npm ERR! mup@1.0.0 prepublish: `nofat make`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the mup@1.0.0 prepublish script 'nofat make'.
> npm ERR! This is most likely a problem with the mup package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     nofat make
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs mup
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!
> npm ERR!     npm owner ls mup
> npm ERR! There is likely additional logging output above.
> `

npm-debug.log:

> `0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'prepublish' ]
> 2 info using npm@2.15.0
> 3 info using node@v4.4.2
> 4 verbose run-script [ 'prepublish' ]
> 5 info prepublish mup@1.0.0
> 6 verbose unsafe-perm in lifecycle true
> 7 info mup@1.0.0 Failed to exec prepublish script
> 8 verbose stack Error: mup@1.0.0 prepublish:`nofat make`
> 8 verbose stack Exit status 1
> 8 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
> 8 verbose stack     at emitTwo (events.js:87:13)
> 8 verbose stack     at EventEmitter.emit (events.js:172:7)
> 8 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
> 8 verbose stack     at emitTwo (events.js:87:13)
> 8 verbose stack     at ChildProcess.emit (events.js:172:7)
> 8 verbose stack     at maybeClose (internal/child_process.js:827:16)
> 8 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
> 9 verbose pkgid mup@1.0.0
> 10 verbose cwd /home/sweaver/meteor-up
> 11 error Linux 3.13.0-79-generic
> 12 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "prepublish"
> 13 error node v4.4.2
> 14 error npm  v2.15.0
> 15 error code ELIFECYCLE
> 16 error mup@1.0.0 prepublish:`nofat make`
> 16 error Exit status 1
> 17 error Failed at the mup@1.0.0 prepublish script 'nofat make'.
> 17 error This is most likely a problem with the mup package,
> 17 error not with npm itself.
> 17 error Tell the author that this fails on your system:
> 17 error     nofat make
> 17 error You can get information on how to open an issue for this project with:
> 17 error     npm bugs mup
> 17 error Or if that isn't available, you can get their info via:
> 17 error
> 17 error     npm owner ls mup
> 17 error There is likely additional logging output above.
> 18 verbose exit [ 1, true ]
> `

Standard Ubuntu 14.04 from DigitalOcean.
Meteor 1.3

Node: v4.4.2
npm: 2.15.0

**Comment by madushan1000** [comment]
@mnmtanish Any idea what's causing this?

**Comment by unmonk** [comment]
Regular mupx also fails with: 

> `Using buildOptions : {}
> events.js:141
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn meteor ENOENT
>     at exports._errnoException (util.js:870:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
>     at onErrorNT (internal/child_process.js:344:16)
>     at nextTickCallbackWith2Args (node.js:442:9)
>     at process._tickCallback (node.js:356:17)
>     at Function.Module.runMain (module.js:443:11)
>     at startup (node.js:139:18)
>     at node.js:968:3
> `

**Comment by thani-sh** [comment]
@unmonk Looks like `meteor-up` didn't install properly. Can you try again after running `npm install` from where you have installed meteor-up (I assume it's `/home/sweaver/meteor-up`).

**Comment by unmonk** [comment]
I have tried that a few time on a few different VMs with no luck.   I was
having an es2015 error first.   Running npm install babel-preset-es2015
--save repaired that.      I also tried grabbing a fresh nofat, but no luck
there.

I will create a fresh droplet tomorrow and start again.  
Do those node and npm version numbers look alright?

**Comment by madushan1000** [comment]
Is `meteor` binary present in PATH on the machine you are trying to run `meteor-up`? 

> Error: spawn meteor ENOENT

Happens when meteor is not installed.

**Comment by gamedevsam** [comment]
Same here, hopefully this helps:

```
root@Jenkins-512mb-nyc3-01:~/meteor-up# npm run prepublish

> mup@1.0.0 prepublish /root/meteor-up
> nofat make

/root/meteor-up/node_modules/nofat/tasks/make/index.js:45
        throw err;
        ^

Error: Couldn't find preset "es2015" relative to directory "/root/meteor-up/src"
    at /root/meteor-up/node_modules/nofat/node_modules/babel-core/lib/transforma                                                                                                             tion/file/options/option-manager.js:372:17
    at Array.map (native)
    at OptionManager.resolvePresets (/root/meteor-up/node_modules/nofat/node_mod                                                                                                             ules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
    at OptionManager.mergePresets (/root/meteor-up/node_modules/nofat/node_modul                                                                                                             es/babel-core/lib/transformation/file/options/option-manager.js:348:10)
    at OptionManager.mergeOptions (/root/meteor-up/node_modules/nofat/node_modul                                                                                                             es/babel-core/lib/transformation/file/options/option-manager.js:307:14)
    at OptionManager.init (/root/meteor-up/node_modules/nofat/node_modules/babel                                                                                                             -core/lib/transformation/file/options/option-manager.js:465:10)
    at File.initOptions (/root/meteor-up/node_modules/nofat/node_modules/babel-c                                                                                                             ore/lib/transformation/file/index.js:194:75)
    at new File (/root/meteor-up/node_modules/nofat/node_modules/babel-core/lib/                                                                                                             transformation/file/index.js:123:22)
    at Pipeline.transform (/root/meteor-up/node_modules/nofat/node_modules/babel                                                                                                             -core/lib/transformation/pipeline.js:45:16)
    at /root/meteor-up/node_modules/nofat/node_modules/babel-core/lib/api/node.j                                                                                                             s:106:18

npm ERR! Linux 3.13.0-77-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "prepublish"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! mup@1.0.0 prepublish: `nofat make`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mup@1.0.0 prepublish script 'nofat make'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mup package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nofat make
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mup
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mup
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/meteor-up/npm-debug.log

```

**UPDATE:** This fixed it: `npm install babel-cli babel-preset-es2015`

**STILL FAILING:**

```
root@Jenkins-512mb-nyc3-01:~/meteor-up# npm run prepublish

> mup@1.0.0 prepublish /root/meteor-up
> nofat make

/root/meteor-up/node_modules/nofat/tasks/make/index.js:45
        throw err;
        ^

Error: Couldn't find preset "stage-3" relative to directory "/root/meteor-up/src"
    at /root/meteor-up/node_modules/nofat/node_modules/babel-core/lib/transformation/file/options/option-manager.js:372:17
    at Array.map (native)
    at OptionManager.resolvePresets (/root/meteor-up/node_modules/nofat/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
    at OptionManager.mergePresets (/root/meteor-up/node_modules/nofat/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
    at OptionManager.mergeOptions (/root/meteor-up/node_modules/nofat/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
    at OptionManager.init (/root/meteor-up/node_modules/nofat/node_modules/babel-core/lib/transformation/file/options/option-manager.js:465:10)
    at File.initOptions (/root/meteor-up/node_modules/nofat/node_modules/babel-core/lib/transformation/file/index.js:194:75)
    at new File (/root/meteor-up/node_modules/nofat/node_modules/babel-core/lib/transformation/file/index.js:123:22)
    at Pipeline.transform (/root/meteor-up/node_modules/nofat/node_modules/babel-core/lib/transformation/pipeline.js:45:16)
    at /root/meteor-up/node_modules/nofat/node_modules/babel-core/lib/api/node.js:106:18

npm ERR! Linux 3.13.0-77-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "prepublish"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! mup@1.0.0 prepublish: `nofat make`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mup@1.0.0 prepublish script 'nofat make'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mup package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nofat make
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mup
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mup
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/meteor-up/npm-debug.log

```

**Comment by maruns** [comment]
I had same issue and additionally  to installing babel running 
`npm install --save-dev babel-preset-stage-3` taken from [https://babeljs.io/docs/plugins/preset-stage-3/](https://babeljs.io/docs/plugins/preset-stage-3/) solved nofat issue.

**Comment by micahalcorn** [comment]
Upgrading npm seems to have solved my `nofat make` issue.

**Comment by madushan1000** [comment]
I hope this issue is resolved now.

**Comment by ayushchd** [comment]
This is still happening. I had to follow @maruns steps to resolve this. Any idea what's causing this issue?

**Comment by madushan1000** [comment]
Try updating to npm3.

**Comment by g41n** [comment]
I've updated to npm3, as @madushan1000 said, and `npm install` presents 2 warnings but works:
```
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use
 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
```

Than `npm link` not works at first but running with `sudo` solved it.

Every `mup` command presents this line, hope is not a problem:
```
(node:1398) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
```

Anyway `mup deploy` fails with this output:
```
(node:1996) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Building App Bundle Locally
[BABEL] Note: The code generator has deoptimised the styling of "/client/scripts/lib/pdfmake.min.js" as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "/client/scripts/lib/vfs_fonts.js" as it exceeds the max of "100KB".
Error If encoding is specified then the first argument must be a string
```

Now I'll try with @maruns steps, as said by @ayushchd, and let you know...

**Comment by g41n** [comment]
Sadly no success, with @ayushchd steps the behaviour is the the same.
I've also tried to follow @ayushchd steps with the LTS version of node (actually 4.4.5) and the result is the one I've pasted in the #140 issue.

**Comment by g41n** [comment]
I've tried to update but no success...
More details here [#140](https://github.com/kadirahq/meteor-up/issues/140#issuecomment-224838202)

**Comment by ilan-schemoul** [comment]
I tried to update npm, `npm install --save-dev npm install babel-cli babel-preset-es2015 babel-preset-stage-3` and install `nofat` from kadira but still I cannot compile locally meteor-up (I need to compile it because even tough let's encrypt PR has been merged it doesn't seems that @zodern has updated npm package)
